//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vsapi.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VehicleApiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VehicleApiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vsapi.Model.VehicleApiResources", typeof(VehicleApiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arunachal Pradesh.
        /// </summary>
        internal static string SateArunachalPredeshText {
            get {
                return ResourceManager.GetString("SateArunachalPredeshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andaman and Nicobar Islands.
        /// </summary>
        internal static string StateAndamanNicorarIslandsText {
            get {
                return ResourceManager.GetString("StateAndamanNicorarIslandsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andra Predesh.
        /// </summary>
        internal static string StateAndraPredeshText {
            get {
                return ResourceManager.GetString("StateAndraPredeshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assam.
        /// </summary>
        internal static string StateAssamText {
            get {
                return ResourceManager.GetString("StateAssamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bihar.
        /// </summary>
        internal static string StateBiharText {
            get {
                return ResourceManager.GetString("StateBiharText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chandigarh.
        /// </summary>
        internal static string StateChandigarhText {
            get {
                return ResourceManager.GetString("StateChandigarhText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chhattisgarh.
        /// </summary>
        internal static string StateChhattisgarhText {
            get {
                return ResourceManager.GetString("StateChhattisgarhText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dadra And Nagar Haveli.
        /// </summary>
        internal static string StateDadraNagarHaveliText {
            get {
                return ResourceManager.GetString("StateDadraNagarHaveliText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daman and Diu.
        /// </summary>
        internal static string StateDamanAndDiuText {
            get {
                return ResourceManager.GetString("StateDamanAndDiuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delhi.
        /// </summary>
        internal static string StateDelhiText {
            get {
                return ResourceManager.GetString("StateDelhiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goa.
        /// </summary>
        internal static string StateGoaText {
            get {
                return ResourceManager.GetString("StateGoaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gujarat.
        /// </summary>
        internal static string StateGujaratText {
            get {
                return ResourceManager.GetString("StateGujaratText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haryana.
        /// </summary>
        internal static string StateHaryanaText {
            get {
                return ResourceManager.GetString("StateHaryanaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Himachal Pradesh.
        /// </summary>
        internal static string StateHimachalPradeshText {
            get {
                return ResourceManager.GetString("StateHimachalPradeshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jammu and Kashmir.
        /// </summary>
        internal static string StateJammuKashmirText {
            get {
                return ResourceManager.GetString("StateJammuKashmirText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jharkhand.
        /// </summary>
        internal static string StateJharkhandText {
            get {
                return ResourceManager.GetString("StateJharkhandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karnataka.
        /// </summary>
        internal static string StateKarnatakaText {
            get {
                return ResourceManager.GetString("StateKarnatakaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerala.
        /// </summary>
        internal static string StateKeralaText {
            get {
                return ResourceManager.GetString("StateKeralaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lakshadweep.
        /// </summary>
        internal static string StateLakshadweepText {
            get {
                return ResourceManager.GetString("StateLakshadweepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madhya Pradesh.
        /// </summary>
        internal static string StateMadhyaPradeshText {
            get {
                return ResourceManager.GetString("StateMadhyaPradeshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra.
        /// </summary>
        internal static string StateMaharashtraText {
            get {
                return ResourceManager.GetString("StateMaharashtraText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipur.
        /// </summary>
        internal static string StateManipurText {
            get {
                return ResourceManager.GetString("StateManipurText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meghalaya.
        /// </summary>
        internal static string StateMeghalayaText {
            get {
                return ResourceManager.GetString("StateMeghalayaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mizoram.
        /// </summary>
        internal static string StateMizoramText {
            get {
                return ResourceManager.GetString("StateMizoramText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagaland.
        /// </summary>
        internal static string StateNagalandText {
            get {
                return ResourceManager.GetString("StateNagalandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odisha.
        /// </summary>
        internal static string StateOdishaText {
            get {
                return ResourceManager.GetString("StateOdishaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puducherry.
        /// </summary>
        internal static string StatePuducherryText {
            get {
                return ResourceManager.GetString("StatePuducherryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punjab.
        /// </summary>
        internal static string StatePunjabText {
            get {
                return ResourceManager.GetString("StatePunjabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rajasthan.
        /// </summary>
        internal static string StateRajasthanText {
            get {
                return ResourceManager.GetString("StateRajasthanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikkim.
        /// </summary>
        internal static string StateSikkimText {
            get {
                return ResourceManager.GetString("StateSikkimText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamil Nadu.
        /// </summary>
        internal static string StateTamilNaduText {
            get {
                return ResourceManager.GetString("StateTamilNaduText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tripura.
        /// </summary>
        internal static string StateTripuraText {
            get {
                return ResourceManager.GetString("StateTripuraText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uttarakhand.
        /// </summary>
        internal static string StateUttarakhandText {
            get {
                return ResourceManager.GetString("StateUttarakhandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uttar Pradesh.
        /// </summary>
        internal static string StateUttarPradeshText {
            get {
                return ResourceManager.GetString("StateUttarPradeshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Bengal.
        /// </summary>
        internal static string StateWestBengalText {
            get {
                return ResourceManager.GetString("StateWestBengalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buses.
        /// </summary>
        internal static string VehicleCategoryBusText {
            get {
                return ResourceManager.GetString("VehicleCategoryBusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        internal static string VehicleCategoryCarText {
            get {
                return ResourceManager.GetString("VehicleCategoryCarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeeps.
        /// </summary>
        internal static string VehicleCategoryJeepText {
            get {
                return ResourceManager.GetString("VehicleCategoryJeepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Motor Vehicles (Goods).
        /// </summary>
        internal static string VehicleCategoryLMVGoodsText {
            get {
                return ResourceManager.GetString("VehicleCategoryLMVGoodsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Motor Vehicles (Passengers).
        /// </summary>
        internal static string VehicleCategoryLMVPassengersText {
            get {
                return ResourceManager.GetString("VehicleCategoryLMVPassengersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiaxled/Articulated Vehicles.
        /// </summary>
        internal static string VehicleCategoryMAVText {
            get {
                return ResourceManager.GetString("VehicleCategoryMAVText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor cycles on hire.
        /// </summary>
        internal static string VehicleCategoryMotorCyclesOnHireText {
            get {
                return ResourceManager.GetString("VehicleCategoryMotorCyclesOnHireText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omni buses.
        /// </summary>
        internal static string VehicleCategoryOmniBusText {
            get {
                return ResourceManager.GetString("VehicleCategoryOmniBusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other vehicles not covered.
        /// </summary>
        internal static string VehicleCategoryOthersText {
            get {
                return ResourceManager.GetString("VehicleCategoryOthersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxis.
        /// </summary>
        internal static string VehicleCategoryTaxiText {
            get {
                return ResourceManager.GetString("VehicleCategoryTaxiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucks &amp; Lorries.
        /// </summary>
        internal static string VehicleCategoryTLText {
            get {
                return ResourceManager.GetString("VehicleCategoryTLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tractors.
        /// </summary>
        internal static string VehicleCategoryTractorText {
            get {
                return ResourceManager.GetString("VehicleCategoryTractorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailers.
        /// </summary>
        internal static string VehicleCategoryTrailerText {
            get {
                return ResourceManager.GetString("VehicleCategoryTrailerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two wheelers.
        /// </summary>
        internal static string VehicleCategoryTwoWheelerText {
            get {
                return ResourceManager.GetString("VehicleCategoryTwoWheelerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        internal static string VehicleTypeCarText {
            get {
                return ResourceManager.GetString("VehicleTypeCarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract carriages.
        /// </summary>
        internal static string VehicleTypeContractCarriageText {
            get {
                return ResourceManager.GetString("VehicleTypeContractCarriageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four to six seaters.
        /// </summary>
        internal static string VehicleTypeFourSixSeaterText {
            get {
                return ResourceManager.GetString("VehicleTypeFourSixSeaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Wheelers.
        /// </summary>
        internal static string VehicleTypeFourWheelerText {
            get {
                return ResourceManager.GetString("VehicleTypeFourWheelerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeeps.
        /// </summary>
        internal static string VehicleTypeJeepText {
            get {
                return ResourceManager.GetString("VehicleTypeJeepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiaxled/Articulated Vehicles.
        /// </summary>
        internal static string VehicleTypeMAVText {
            get {
                return ResourceManager.GetString("VehicleTypeMAVText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxi cabs.
        /// </summary>
        internal static string VehicleTypeMaxiCabText {
            get {
                return ResourceManager.GetString("VehicleTypeMaxiCabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mopeds.
        /// </summary>
        internal static string VehicleTypeMopedText {
            get {
                return ResourceManager.GetString("VehicleTypeMopedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor cabs.
        /// </summary>
        internal static string VehicleTypeMotorCabText {
            get {
                return ResourceManager.GetString("VehicleTypeMotorCabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor cycles on hire.
        /// </summary>
        internal static string VehicleTypeMotorCycleOnHireText {
            get {
                return ResourceManager.GetString("VehicleTypeMotorCycleOnHireText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor cycles.
        /// </summary>
        internal static string VehicleTypeMotorCycleText {
            get {
                return ResourceManager.GetString("VehicleTypeMotorCycleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omni buses.
        /// </summary>
        internal static string VehicleTypeOmniBusText {
            get {
                return ResourceManager.GetString("VehicleTypeOmniBusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other buses.
        /// </summary>
        internal static string VehicleTypeOtherBusText {
            get {
                return ResourceManager.GetString("VehicleTypeOtherBusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other taxis.
        /// </summary>
        internal static string VehicleTypeOtherTaxiText {
            get {
                return ResourceManager.GetString("VehicleTypeOtherTaxiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other vehicles not covered.
        /// </summary>
        internal static string VehicleTypeOtherVehicleText {
            get {
                return ResourceManager.GetString("VehicleTypeOtherVehicleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private service vehicles.
        /// </summary>
        internal static string VehicleTypePrivateServiceVehicleText {
            get {
                return ResourceManager.GetString("VehicleTypePrivateServiceVehicleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scooters.
        /// </summary>
        internal static string VehicleTypeScooterText {
            get {
                return ResourceManager.GetString("VehicleTypeScooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage carriages.
        /// </summary>
        internal static string VehicleTypeStageCarriageText {
            get {
                return ResourceManager.GetString("VehicleTypeStageCarriageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three seaters.
        /// </summary>
        internal static string VehicleTypeThreeSeaterText {
            get {
                return ResourceManager.GetString("VehicleTypeThreeSeaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Wheelers.
        /// </summary>
        internal static string VehicleTypeThreeWheelerText {
            get {
                return ResourceManager.GetString("VehicleTypeThreeWheelerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucks &amp; Lorries.
        /// </summary>
        internal static string VehicleTypeTLText {
            get {
                return ResourceManager.GetString("VehicleTypeTLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tractors.
        /// </summary>
        internal static string VehicleTypeTractorText {
            get {
                return ResourceManager.GetString("VehicleTypeTractorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailers.
        /// </summary>
        internal static string VehicleTypeTrailerText {
            get {
                return ResourceManager.GetString("VehicleTypeTrailerText", resourceCulture);
            }
        }
    }
}
